-- Day 47: Real-World Sales Analysis
-- Queries: Q461 to Q470
-- Database: MySQL / PostgreSQL

-- Assumed table:
-- sales(
--     sale_id,
--     customer_id,
--     product_id,
--     category,
--     sale_date,
--     quantity,
--     price
-- )

-- =========================================
-- Q461: Calculate total sales revenue
-- =========================================
SELECT SUM(quantity * price) AS total_revenue
FROM sales;


-- =========================================
-- Q462: Calculate total quantity sold
-- =========================================
SELECT SUM(quantity) AS total_quantity
FROM sales;


-- =========================================
-- Q463: Calculate total revenue for each category
-- =========================================
SELECT category,
       SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY category;


-- =========================================
-- Q464: Find the category with the highest revenue
-- =========================================
SELECT category,
       SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;


-- =========================================
-- Q465: Find total revenue generated by each customer
-- =========================================
SELECT customer_id,
       SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY customer_id;


-- =========================================
-- Q466: Find the top 5 customers by total spending
-- =========================================
SELECT customer_id,
       SUM(quantity * price) AS total_spending
FROM sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 5;


-- =========================================
-- Q467: Find the total number of sales transactions
-- =========================================
SELECT COUNT(*) AS total_transactions
FROM sales;


-- =========================================
-- Q468: Calculate the average order value
-- =========================================
SELECT AVG(quantity * price) AS average_order_value
FROM sales;


-- =========================================
-- Q469: Find daily total revenue
-- =========================================
SELECT sale_date,
       SUM(quantity * price) AS daily_revenue
FROM sales
GROUP BY sale_date
ORDER BY sale_date;


-- =========================================
-- Q470: Find the highest-value sales transaction
-- =========================================
SELECT *,
       quantity * price AS sale_amount
FROM sales
ORDER BY sale_amount DESC
LIMIT 1;
