-- Day 49: Advanced Sales Analysis
-- Queries: Q481 to Q490
-- Database: MySQL / PostgreSQL

-- Assumed table:
-- sales(
--     sale_id,
--     customer_id,
--     product_id,
--     category,
--     sale_date,
--     quantity,
--     price
-- )

-- =========================================
-- Q481: Find the highest revenue generated by each category
-- =========================================
SELECT category,
       MAX(quantity * price) AS highest_transaction
FROM sales
GROUP BY category;


-- =========================================
-- Q482: Find the average transaction value for each category
-- =========================================
SELECT category,
       AVG(quantity * price) AS average_transaction
FROM sales
GROUP BY category;


-- =========================================
-- Q483: Find the total revenue generated each year
-- =========================================
SELECT YEAR(sale_date) AS sale_year,
       SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY YEAR(sale_date)
ORDER BY sale_year;


-- =========================================
-- Q484: Find the highest-revenue year
-- =========================================
SELECT YEAR(sale_date) AS sale_year,
       SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY YEAR(sale_date)
ORDER BY total_revenue DESC
LIMIT 1;


-- =========================================
-- Q485: Find customers who made more than 5 transactions
-- =========================================
SELECT customer_id,
       COUNT(*) AS total_transactions
FROM sales
GROUP BY customer_id
HAVING COUNT(*) > 5;


-- =========================================
-- Q486: Find products sold in more than one category
-- =========================================
SELECT product_id,
       COUNT(DISTINCT category) AS category_count
FROM sales
GROUP BY product_id
HAVING COUNT(DISTINCT category) > 1;


-- =========================================
-- Q487: Find the highest-spending customer in each category
-- =========================================
WITH customer_category_sales AS (
    SELECT category,
           customer_id,
           SUM(quantity * price) AS total_spending
    FROM sales
    GROUP BY category, customer_id
),
ranked_customers AS (
    SELECT *,
           DENSE_RANK() OVER (
               PARTITION BY category
               ORDER BY total_spending DESC
           ) AS spending_rank
    FROM customer_category_sales
)
SELECT *
FROM ranked_customers
WHERE spending_rank = 1;


-- =========================================
-- Q488: Find each product's percentage contribution to total revenue
-- =========================================
WITH product_revenue AS (
    SELECT product_id,
           SUM(quantity * price) AS total_revenue
    FROM sales
    GROUP BY product_id
)
SELECT product_id,
       total_revenue,
       ROUND(
           total_revenue * 100.0 /
           SUM(total_revenue) OVER (),
           2
       ) AS revenue_percentage
FROM product_revenue;


-- =========================================
-- Q489: Find running total of daily revenue
-- =========================================
WITH daily_revenue AS (
    SELECT sale_date,
           SUM(quantity * price) AS total_revenue
    FROM sales
    GROUP BY sale_date
)
SELECT sale_date,
       total_revenue,
       SUM(total_revenue) OVER (
           ORDER BY sale_date
       ) AS running_revenue
FROM daily_revenue;


-- =========================================
-- Q490: Find the top 3 products in each category by revenue
-- =========================================
WITH product_category_revenue AS (
    SELECT category,
           product_id,
           SUM(quantity * price) AS total_revenue
    FROM sales
    GROUP BY category, product_id
),
ranked_products AS (
    SELECT *,
           DENSE_RANK() OVER (
               PARTITION BY category
               ORDER BY total_revenue DESC
           ) AS revenue_rank
    FROM product_category_revenue
)
SELECT *
FROM ranked_products
WHERE revenue_rank <= 3;
