-- Day 60: E-Commerce SQL Capstone
-- Queries: Q591 to Q600
-- Database: MySQL 8 / PostgreSQL

-- Assumed tables:
-- customers(customer_id, customer_name, city)
-- products(product_id, product_name, category, price, cost_price)
-- orders(order_id, customer_id, order_date, status)
-- order_items(order_id, product_id, quantity, price)


-- Q591: Find the total revenue generated by each customer
SELECT o.customer_id,
       SUM(oi.quantity * oi.price) AS total_revenue
FROM orders o
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY total_revenue DESC;


-- Q592: Rank all customers based on their total revenue
WITH customer_revenue AS (
    SELECT o.customer_id,
           SUM(oi.quantity * oi.price) AS total_revenue
    FROM orders o
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)
SELECT customer_id,
       total_revenue,
       DENSE_RANK() OVER (
           ORDER BY total_revenue DESC
       ) AS revenue_rank
FROM customer_revenue
ORDER BY revenue_rank;


-- Q593: Find the top 3 customers from each city
WITH customer_revenue AS (
    SELECT c.customer_id,
           c.customer_name,
           c.city,
           SUM(oi.quantity * oi.price) AS total_revenue
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id,
             c.customer_name,
             c.city
),
ranked_customers AS (
    SELECT *,
           DENSE_RANK() OVER (
               PARTITION BY city
               ORDER BY total_revenue DESC
           ) AS city_rank
    FROM customer_revenue
)
SELECT customer_id,
       customer_name,
       city,
       total_revenue,
       city_rank
FROM ranked_customers
WHERE city_rank <= 3
ORDER BY city, city_rank;


-- Q594: Find the revenue generated by each category
-- and its percentage of total revenue
WITH category_revenue AS (
    SELECT p.category,
           SUM(oi.quantity * oi.price) AS revenue
    FROM products p
    INNER JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.category
)
SELECT category,
       revenue,
       ROUND(
           revenue * 100.0 /
           SUM(revenue) OVER (),
           2
       ) AS revenue_percentage
FROM category_revenue
ORDER BY revenue DESC;


-- Q595: Find the highest-revenue product in each city
WITH city_product_revenue AS (
    SELECT c.city,
           p.product_id,
           p.product_name,
           SUM(oi.quantity * oi.price) AS revenue
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    INNER JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.city,
             p.product_id,
             p.product_name
),
ranked_products AS (
    SELECT *,
           RANK() OVER (
               PARTITION BY city
               ORDER BY revenue DESC
           ) AS product_rank
    FROM city_product_revenue
)
SELECT city,
       product_id,
       product_name,
       revenue
FROM ranked_products
WHERE product_rank = 1
ORDER BY city;


-- Q596: Find customers whose spending is higher
-- than the average spending of customers in their city
WITH customer_spending AS (
    SELECT c.customer_id,
           c.customer_name,
           c.city,
           SUM(oi.quantity * oi.price) AS spending
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id,
             c.customer_name,
             c.city
),
city_analysis AS (
    SELECT *,
           AVG(spending) OVER (
               PARTITION BY city
           ) AS city_average_spending
    FROM customer_spending
)
SELECT customer_id,
       customer_name,
       city,
       spending,
       city_average_spending
FROM city_analysis
WHERE spending > city_average_spending
ORDER BY city, spending DESC;


-- Q597: Find the month with the highest revenue
WITH monthly_revenue AS (
    SELECT
        EXTRACT(YEAR FROM o.order_date) AS order_year,
        EXTRACT(MONTH FROM o.order_date) AS order_month,
        SUM(oi.quantity * oi.price) AS revenue
    FROM orders o
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        EXTRACT(YEAR FROM o.order_date),
        EXTRACT(MONTH FROM o.order_date)
)
SELECT order_year,
       order_month,
       revenue
FROM monthly_revenue
WHERE revenue = (
    SELECT MAX(revenue)
    FROM monthly_revenue
);


-- Q598: Find products that are above average in both
-- quantity sold and revenue
WITH product_metrics AS (
    SELECT p.product_id,
           p.product_name,
           SUM(oi.quantity) AS quantity_sold,
           SUM(oi.quantity * oi.price) AS revenue
    FROM products p
    INNER JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_id,
             p.product_name
)
SELECT *
FROM product_metrics
WHERE quantity_sold > (
          SELECT AVG(quantity_sold)
          FROM product_metrics
      )
  AND revenue > (
          SELECT AVG(revenue)
          FROM product_metrics
      )
ORDER BY revenue DESC;


-- Q599: Calculate each customer's first order value,
-- latest order value and change between them
WITH order_totals AS (
    SELECT o.customer_id,
           o.order_id,
           o.order_date,
           SUM(oi.quantity * oi.price) AS order_value
    FROM orders o
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id,
             o.order_id,
             o.order_date
),
customer_orders AS (
    SELECT *,
           FIRST_VALUE(order_value) OVER (
               PARTITION BY customer_id
               ORDER BY order_date, order_id
           ) AS first_order_value,

           FIRST_VALUE(order_value) OVER (
               PARTITION BY customer_id
               ORDER BY order_date DESC, order_id DESC
           ) AS latest_order_value
    FROM order_totals
)
SELECT DISTINCT
       customer_id,
       first_order_value,
       latest_order_value,
       latest_order_value - first_order_value
           AS order_value_change
FROM customer_orders
ORDER BY customer_id;


-- Q600: Create a complete customer performance report
WITH customer_metrics AS (
    SELECT
        c.customer_id,
        c.customer_name,
        c.city,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(oi.quantity * oi.price) AS total_revenue,
        AVG(oi.quantity * oi.price) AS average_item_value,
        MAX(o.order_date) AS last_order_date
    FROM customers c
    INNER JOIN orders o
        ON c.customer_id = o.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_id,
             c.customer_name,
             c.city
),
ranked_customers AS (
    SELECT *,
           DENSE_RANK() OVER (
               ORDER BY total_revenue DESC
           ) AS revenue_rank
    FROM customer_metrics
)
SELECT customer_id,
       customer_name,
       city,
       total_orders,
       total_revenue,
       ROUND(average_item_value, 2) AS average_item_value,
       last_order_date,
       revenue_rank,
       CASE
           WHEN total_revenue >= 100000
                AND total_orders >= 5
               THEN 'VIP'

           WHEN total_revenue >= 50000
                AND total_orders >= 3
               THEN 'High Value'

           WHEN total_revenue >= 20000
               THEN 'Regular'

           ELSE 'Low Value'
       END AS customer_segment
FROM ranked_customers
ORDER BY revenue_rank;
