-- ============================================================
-- Day 63: Advanced SQL Business Intelligence
-- Queries: Q621 to Q630
-- Database: MySQL / PostgreSQL
--
-- Assumed Tables:
--
-- customers(
--     customer_id,
--     customer_name,
--     city
-- )
--
-- products(
--     product_id,
--     product_name,
--     category,
--     price,
--     cost_price
-- )
--
-- orders(
--     order_id,
--     customer_id,
--     order_date,
--     status
-- )
--
-- order_items(
--     order_id,
--     product_id,
--     quantity,
--     price
-- )
-- ============================================================


-- ============================================================
-- Q621: Customer Lifetime Value
-- ============================================================
-- Task:
-- Calculate the lifetime value of every customer.
--
-- LTV = Total revenue generated by the customer.
--
-- Concepts:
-- Customer Lifetime Value
-- COUNT()
-- SUM()
-- GROUP BY
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,

    COUNT(DISTINCT o.order_id) AS total_orders,

    SUM(oi.quantity * oi.price) AS lifetime_value

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

GROUP BY
    c.customer_id,
    c.customer_name

ORDER BY
    lifetime_value DESC;


-- ============================================================
-- Q622: Top 10% Customers by Revenue
-- ============================================================
-- Task:
-- Find customers belonging to the top 10%
-- based on total revenue.
--
-- Concepts:
-- NTILE()
-- Decile Analysis
-- Customer Ranking
-- CTE
-- ============================================================

WITH customer_revenue AS (

    SELECT
        c.customer_id,
        c.customer_name,

        SUM(oi.quantity * oi.price) AS revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.customer_name
),

ranked_customers AS (

    SELECT
        customer_id,
        customer_name,
        revenue,

        NTILE(10) OVER (
            ORDER BY revenue DESC
        ) AS revenue_decile

    FROM customer_revenue
)

SELECT
    customer_id,
    customer_name,
    revenue,
    revenue_decile

FROM ranked_customers

WHERE revenue_decile = 1

ORDER BY
    revenue DESC;


-- ============================================================
-- Q623: Three-Month Rolling Revenue
-- ============================================================
-- Task:
-- Calculate monthly revenue and
-- 3-month rolling revenue.
--
-- Concepts:
-- Window SUM()
-- Rolling Window
-- ROWS BETWEEN
-- Time-Series Analysis
-- ============================================================

WITH monthly_revenue AS (

    SELECT
        EXTRACT(YEAR FROM o.order_date) AS order_year,
        EXTRACT(MONTH FROM o.order_date) AS order_month,

        SUM(
            oi.quantity * oi.price
        ) AS revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        EXTRACT(YEAR FROM o.order_date),
        EXTRACT(MONTH FROM o.order_date)
)

SELECT
    order_year,
    order_month,
    revenue,

    SUM(revenue) OVER (
        ORDER BY order_year, order_month
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS rolling_3_month_revenue

FROM monthly_revenue

ORDER BY
    order_year,
    order_month;


-- ============================================================
-- Q624: Three-Month Moving Average
-- ============================================================
-- Task:
-- Calculate the 3-month moving average
-- of monthly revenue.
--
-- Concepts:
-- Window AVG()
-- Moving Average
-- Time-Series Analysis
-- ============================================================

WITH monthly_revenue AS (

    SELECT
        EXTRACT(YEAR FROM o.order_date) AS order_year,
        EXTRACT(MONTH FROM o.order_date) AS order_month,

        SUM(
            oi.quantity * oi.price
        ) AS revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        EXTRACT(YEAR FROM o.order_date),
        EXTRACT(MONTH FROM o.order_date)
)

SELECT
    order_year,
    order_month,
    revenue,

    ROUND(
        AVG(revenue) OVER (
            ORDER BY order_year, order_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS moving_3_month_average

FROM monthly_revenue

ORDER BY
    order_year,
    order_month;


-- ============================================================
-- Q625: Products With High Quantity but Low Revenue
-- ============================================================
-- Task:
-- Find products that:
--
-- 1. Sell more than the average quantity
-- 2. Generate less than the average revenue
--
-- This can identify low-value/high-volume products.
--
-- Concepts:
-- Window AVG()
-- Business Analysis
-- Anomaly Detection
-- CTE
-- ============================================================

WITH product_sales AS (

    SELECT
        p.product_id,
        p.product_name,

        SUM(oi.quantity) AS total_quantity,

        SUM(
            oi.quantity * oi.price
        ) AS revenue

    FROM products p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.product_id,
        p.product_name
),

benchmarks AS (

    SELECT
        product_id,
        product_name,
        total_quantity,
        revenue,

        AVG(total_quantity) OVER ()
            AS average_quantity,

        AVG(revenue) OVER ()
            AS average_revenue

    FROM product_sales
)

SELECT
    product_id,
    product_name,
    total_quantity,
    revenue,
    average_quantity,
    average_revenue

FROM benchmarks

WHERE total_quantity > average_quantity
  AND revenue < average_revenue

ORDER BY
    total_quantity DESC;


-- ============================================================
-- Q626: Product Profit Margin
-- ============================================================
-- Task:
-- Calculate:
--
-- 1. Total revenue
-- 2. Total cost
-- 3. Total profit
-- 4. Profit margin percentage
--
-- Formula:
--
-- Profit = Revenue - Cost
--
-- Profit Margin =
-- Profit / Revenue * 100
--
-- Concepts:
-- Business Metrics
-- Profit Analysis
-- NULLIF()
-- ============================================================

SELECT
    p.product_id,
    p.product_name,

    SUM(
        oi.quantity * oi.price
    ) AS total_revenue,

    SUM(
        oi.quantity * p.cost_price
    ) AS total_cost,

    SUM(
        oi.quantity *
        (oi.price - p.cost_price)
    ) AS total_profit,

    ROUND(
        SUM(
            oi.quantity *
            (oi.price - p.cost_price)
        ) * 100.0
        /
        NULLIF(
            SUM(oi.quantity * oi.price),
            0
        ),
        2
    ) AS profit_margin_percentage

FROM products p

JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_id,
    p.product_name

ORDER BY
    total_profit DESC;


-- ============================================================
-- Q627: Highest-Profit Product in Each Category
-- ============================================================
-- Task:
-- Find the highest-profit product from every category.
--
-- If multiple products have the same profit,
-- return all tied products.
--
-- Concepts:
-- DENSE_RANK()
-- PARTITION BY
-- Profit Analysis
-- CTE
-- ============================================================

WITH product_profit AS (

    SELECT
        p.product_id,
        p.product_name,
        p.category,

        SUM(
            oi.quantity *
            (oi.price - p.cost_price)
        ) AS total_profit

    FROM products p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.product_id,
        p.product_name,
        p.category
),

ranked_products AS (

    SELECT
        product_id,
        product_name,
        category,
        total_profit,

        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY total_profit DESC
        ) AS profit_rank

    FROM product_profit
)

SELECT
    product_id,
    product_name,
    category,
    total_profit

FROM ranked_products

WHERE profit_rank = 1

ORDER BY
    category;


-- ============================================================
-- Q628: Customers With Orders in Consecutive Months
-- ============================================================
-- Task:
-- Find customers who placed orders in consecutive
-- calendar months.
--
-- Example:
--
-- January -> February
-- February -> March
-- November -> December
-- December -> January
--
-- Concepts:
-- LAG()
-- Consecutive Period Detection
-- Window Functions
-- ============================================================

WITH customer_months AS (

    SELECT DISTINCT
        customer_id,

        EXTRACT(YEAR FROM order_date)
            AS order_year,

        EXTRACT(MONTH FROM order_date)
            AS order_month

    FROM orders
),

numbered_months AS (

    SELECT
        customer_id,
        order_year,
        order_month,

        LAG(order_year) OVER (
            PARTITION BY customer_id
            ORDER BY order_year, order_month
        ) AS previous_year,

        LAG(order_month) OVER (
            PARTITION BY customer_id
            ORDER BY order_year, order_month
        ) AS previous_month

    FROM customer_months
)

SELECT
    customer_id,
    order_year,
    order_month,
    previous_year,
    previous_month

FROM numbered_months

WHERE
    (
        order_year = previous_year
        AND order_month = previous_month + 1
    )

    OR

    (
        order_year = previous_year + 1
        AND order_month = 1
        AND previous_month = 12
    )

ORDER BY
    customer_id,
    order_year,
    order_month;


-- ============================================================
-- Q629: Category Revenue Contribution Percentage
-- ============================================================
-- Task:
-- Calculate:
--
-- 1. Revenue for every category
-- 2. Percentage contribution of each category
--    to total revenue.
--
-- Concepts:
-- Window SUM()
-- Percentage Contribution
-- Business Intelligence
-- ============================================================

WITH category_revenue AS (

    SELECT
        p.category,

        SUM(
            oi.quantity * oi.price
        ) AS revenue

    FROM products p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.category
)

SELECT
    category,
    revenue,

    ROUND(
        revenue * 100.0
        /
        NULLIF(
            SUM(revenue) OVER (),
            0
        ),
        2
    ) AS revenue_percentage

FROM category_revenue

ORDER BY
    revenue DESC;


-- ============================================================
-- Q630: Customer Revenue Rank Within City
-- ============================================================
-- Task:
-- Rank customers by revenue within their city.
--
-- If two customers have the same revenue,
-- they receive the same rank.
--
-- Concepts:
-- DENSE_RANK()
-- PARTITION BY
-- City-Level Ranking
-- Customer Analytics
-- ============================================================

WITH customer_revenue AS (

    SELECT
        c.customer_id,
        c.customer_name,
        c.city,

        SUM(
            oi.quantity * oi.price
        ) AS revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.customer_name,
        c.city
),

ranked_customers AS (

    SELECT
        customer_id,
        customer_name,
        city,
        revenue,

        DENSE_RANK() OVER (
            PARTITION BY city
            ORDER BY revenue DESC
        ) AS city_revenue_rank

    FROM customer_revenue
)

SELECT
    customer_id,
    customer_name,
    city,
    revenue,
    city_revenue_rank

FROM ranked_customers

ORDER BY
    city,
    city_revenue_rank;


-- ============================================================
-- END OF DAY 63
-- Queries: Q621 - Q630
-- Progress: 630 / 1000 = 63%
-- ============================================================
